name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci-build.yaml
      - .github/actions/build-push-grapevine/**
      - cmd/**
      - internal/**
      - Dockerfile
      - go.*
      - web/**
      - .npmrc
      - biome.jsonc
      - package.json
      - packge-lock.json
      - tsconfig.json
      - vite.config.ts

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
          # We need the entire history to determine the current version
          fetch-depth: 0

      - name: Determine tag
        id: determine_tag
        env:
          GITHUB_PR: ${{ github.event.number }}
        run: |
          echo "tag=pr-$GITHUB_PR" >> "$GITHUB_OUTPUT"
          echo -n "revision=" >> "$GITHUB_OUTPUT"
          git describe >> "$GITHUB_OUTPUT"
          echo -n "date=" >> "$GITHUB_OUTPUT"
          date --iso-8601=seconds >> "$GITHUB_OUTPUT"

      - name: Build
        uses: ./.github/actions/build-push-grapevine
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.determine_tag.outputs.tag }}
          revision: ${{ steps.determine_tag.outputs.revision }}
          date: ${{ steps.determine_tag.outputs.date }}
